### ISSUE TITLE
About the BERT + BiL method

### ISSUE THREAD

**Issue by zetaoLian** [YifeiZhou02/Improve-Discourse-Dependency-Parsing-with-Contextualized-Representations#1]
Hello~! May I ask if there is a training code about the BERT + BiL method for relation identification? Thanks!!

**Comment by YifeiZhou02** [comment]
We’ve included the training code of all of the components in “run.sh” file, you can also check out “train_relation.py” for details of training relation identification components. The script needs to first train the BERT then train BiLSTM separately, which might need some tuning. I remember that sequence labeling works the best for SciDTB in inter-sentential level and for CDTB in intra-sentential level.
